import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateAtomicProductionReleaseControl } from '../scripts/worldstage-atomic-production-release-control.mjs';
import { assembleProductionEvidenceArtifact } from '../scripts/worldstage-production-evidence-artifact.mjs';
import { verifyProductionEvidenceBundle } from '../scripts/worldstage-production-evidence-verification-adapter.mjs';
import { createAdapterVerificationEnvelope, consumeAdapterVerificationEnvelope } from '../scripts/worldstage-production-gate-consumption.mjs';
import { evaluateProductionReleaseGate } from '../scripts/worldstage-production-release-gate.mjs';
const SOURCE='a'.repeat(40), PREVIEW='dpl_preview_candidate', PROD='dpl_preserved_production', NOW='2026-08-12T08:00:00.000Z';
function evidence(source=SOURCE, preview=PREVIEW) { return {prior_run:{schema:'worldstage.prior-run-evidence.v1',project_key:'worldstage-cherry',repository:'banataosystems/nlp',source_sha:source,run_id:70001,artifact_name:'worldstage-production-evidence',conclusion:'success'},live_staging:{schema:'worldstage.live-staging-evidence.v1',project_key:'worldstage-cherry',repository:'banataosystems/nlp',source_sha:source,kind:'live-staging',result:'PASS',confidential_data_used:false,production_accessed:false,preview_deployment_id:preview,production_deployment_id:PROD},physical_device:{schema:'worldstage.physical-device-acceptance.v1',project_key:'worldstage-cherry',repository:'banataosystems/nlp',source_sha:source,result:'PASS',reviewer_role:'owner',preview_deployment_id:preview},rollback:{schema:'worldstage.rollback-evidence.v1',project_key:'worldstage-cherry',repository:'banataosystems/nlp',source_sha:source,result:'VERIFIED',rollback_target_sha:'b'.repeat(40),production_mutated_during_proof:false},governance:{schema:'worldstage.governance-evidence.v1',project_key:'worldstage-cherry',repository:'banataosystems/nlp',source_sha:source,status:'SYNCED'}}; }
function resolvedLedger(){const rows=['| ID | Topic | Status | Decision value | Approved by | Date | Evidence/source | Implementation impact |','|---|---|---|---|---|---|---|---|'],blocks=[];for(let i=1;i<=24;i++){const id=`D${i}`;rows.push(`| ${id} | Synthetic ${id} | RESOLVED | Synthetic ${id} | Authorized Owner | 2026-08-12 | synthetic:${id} | Synthetic |`);blocks.push([`Decision ID: ${id}`,'Status: RESOLVED',`Decision value: Synthetic ${id}`,'Approved by: Authorized Owner','Approval date: 2026-08-12',`Evidence/source: synthetic:${id}`,'Rationale: Synthetic regression only','Exceptions: NONE','Implementation impact: Synthetic regression only'].join('\n'));}return `${rows.join('\n')}\n\n${blocks.join('\n\n')}\n`;}
function context(o={}){return {sourceSha:SOURCE,currentRunId:80001,currentRunAttempt:1,expectedPriorRunId:70001,expectedPriorArtifactName:'worldstage-production-evidence',expectedPreviewDeploymentId:PREVIEW,productionDeploymentId:PROD,now:NOW,maxAdapterAgeSeconds:600,adapterGeneratedAt:'2026-08-12T07:55:00.000Z',adapterExpiresAt:'2026-08-12T08:05:00.000Z',...o};}
test('complete synthetic chain reaches readiness but never grants production authority',()=>{const r=evaluateAtomicProductionReleaseControl({evidence:evidence(),ledgerMarkdown:resolvedLedger(),context:context()});assert.equal(r.accepted,true);assert.equal(r.production_gate.grants_production_authority,false);});
test('raw evidence bundle cannot bypass adapter consumption',()=>{const a=assembleProductionEvidenceArtifact({sourceSha:SOURCE,priorRunId:70001,priorRunArtifactName:'worldstage-production-evidence',previewDeploymentId:PREVIEW,evidence:evidence()});const r=evaluateProductionReleaseGate({consumedEvidence:a.bundle,ledgerMarkdown:resolvedLedger(),context:context()});assert.equal(r.accepted,false);});
test('stale and replayed adapter output fail closed',()=>{const stale=evaluateAtomicProductionReleaseControl({evidence:evidence(),ledgerMarkdown:resolvedLedger(),context:context({adapterGeneratedAt:'2026-08-12T07:40:00.000Z'})});assert.equal(stale.stage,'gate-consumption');const a=assembleProductionEvidenceArtifact({sourceSha:SOURCE,priorRunId:70001,priorRunArtifactName:'worldstage-production-evidence',previewDeploymentId:PREVIEW,evidence:evidence()});const v=verifyProductionEvidenceBundle({bundle:a.bundle,artifactsByDigest:a.artifactsByDigest});const env=createAdapterVerificationEnvelope({adapterResult:v,verificationRunId:80001,verificationRunAttempt:1,generatedAt:'2026-08-12T07:55:00Z',expiresAt:'2026-08-12T08:05:00Z'});const seen=new Set();assert.equal(consumeAdapterVerificationEnvelope({envelope:env,context:context(),consumedDigests:seen}).accepted,true);assert.equal(consumeAdapterVerificationEnvelope({envelope:env,context:context(),consumedDigests:seen}).accepted,false);});
test('missing upstream digest cannot be enveloped',()=>{const a=assembleProductionEvidenceArtifact({sourceSha:SOURCE,priorRunId:70001,priorRunArtifactName:'worldstage-production-evidence',previewDeploymentId:PREVIEW,evidence:evidence()});const v=verifyProductionEvidenceBundle({bundle:a.bundle,artifactsByDigest:a.artifactsByDigest});delete v.production_gate_input.verified_section_digests.rollback;assert.throws(()=>createAdapterVerificationEnvelope({adapterResult:v,verificationRunId:80001,verificationRunAttempt:1,generatedAt:'2026-08-12T07:55:00Z',expiresAt:'2026-08-12T08:05:00Z'}));});
test('all-open governance blocks',()=>{const rows=['| ID | Topic | Status | Decision value | Approved by | Date | Evidence/source | Implementation impact |','|---|---|---|---|---|---|---|---|'];for(let i=1;i<=24;i++)rows.push(`| D${i} | Synthetic | OPEN | — | — | — | — | Blocked |`);const r=evaluateAtomicProductionReleaseControl({evidence:evidence(),ledgerMarkdown:rows.join('\n'),context:context()});assert.equal(r.accepted,false);assert.ok(r.production_gate.blockers.some(x=>x.code==='PRODUCTION_DECISIONS_OPEN'));});
